### ISSUE TITLE
build error with updated debian 6

### ISSUE THREAD

**Issue by sraihan** [CPqD/ofdissector#4]
root@debian-6:/home/user/ofdissector/src# scons install
scons: Reading SConscript files ...
scons: done reading SConscript files.
scons: Building targets ...
g++ -o util/FieldManager.os -c -fPIC -I. -I/usr/include/wireshark -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include util/FieldManager.cpp
util/FieldManager.cpp: In member function 'void FieldManager::createField(std::string, const char_, ftenum, int, const void_, guint32, bool)':
util/FieldManager.cpp:42: error: 'struct header_field_info' has no member named 'ref_type'
util/FieldManager.cpp:42: error: 'HF_REF_TYPE_NONE' was not declared in this scope
scons: **\* [util/FieldManager.os] Error 1
scons: building terminated because of errors.

**Comment by rnudechu** [comment]
Same problem occurs with Ubuntu 10.04

**Comment by rnudechu** [comment]
Looks like the problem mentioned above can be resolved by simply commenting out the offending line. The openflow.so file created looks like it works with dissecting openflow 1.3 traffic properly. (This is based on limited testing with trema-edge learning switch)

In FieldManager.cpp include two slash (//) at the beginning of line 42:

// hfri.hfinfo.ref_type = HF_REF_TYPE_NONE;
